language: "vi"

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
    lowercase: true
  - name: CountVectorsFeaturizer
    lowercase: true
  - name: DIETClassifier
    epochs: 100
    entity_threshold: 0.5
    intent_threshold: 0.5
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.5
    # ambiguity_threshold: 0.5
  - name: NLUCommandAdapter

policies:
  - name: RulePolicy
    core_fallback_action_name: "action_listen"
    enable_fallback_prediction: false
  - name: MemoizationPolicy
    max_history: 10
  - name: TEDPolicy
    max_history: 10
    epochs: 100
  - name: FlowPolicy