language: "en"

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
    lowercase: true
  - name: CountVectorsFeaturizer
    lowercase: true
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.2
  - name: NLUCommandAdapter

policies:
  - name: MemoizationPolicy
    max_history: 15
  - name: TEDPolicy
    max_history: 15
    epochs: 100
  - name: RulePolicy
    core_fallback_threshold: 0.2
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true