name: Rasa Pro CI-CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  train_and_deploy:
    runs-on: poptech

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Rasa Pro image
        run: |
          sudo docker pull ${{ vars.RASA_IMAGE }}

      - name: Train Rasa model with Rasa Pro
        run: |
          echo ${GITHUB_WORKSPACE} && ls ${GITHUB_WORKSPACE} && sudo docker run --rm -v ${GITHUB_WORKSPACE}:/app \
            -e RASA_PRO_LICENSE=${{ secrets.RASA_PRO_LICENSE }} \
            -u $(id -u) \
            ${{ vars.RASA_IMAGE }} \
            train -c /app/config.yml --domain /app/domain.yml --endpoints /app/endpoints.yml --data /app/data --out /app/models

      - name: Stop current container
        run: |
          sudo docker container stop github_runner_dgcas2024_rasa && sudo docker container rm github_runner_dgcas2024_rasa
        continue-on-error: true

      - name: Run model
        run: |
          sudo docker run --restart unless-stopped -d -v ${GITHUB_WORKSPACE}:/app \
            -e RASA_PRO_LICENSE=${{ secrets.RASA_PRO_LICENSE }} \
            -e FACEBOOK_VERIFY=${FACEBOOK_VERIFY} \
            -e FACEBOOK_SECRET=${FACEBOOK_SECRET} \
            -e FACEBOOK_PAGE_ACCESS_TOKEN=${FACEBOOK_PAGE_ACCESS_TOKEN} \
            -u $(id -u) \
            --name github_runner_dgcas2024_rasa \
            -p 5005:5005 \
            ${{ vars.RASA_IMAGE }} \
            run --model /app2/models --endpoints /app2/endpoints.yml --credentials /app2/credentials.yml --enable-api --cors *
          echo "Waiting for server to be ready..."
          timeout=300
          while ! curl --output /dev/null --silent --fail http://127.0.0.1:5005; do
            echo "Waiting for server to be ready...$timeout"
            sleep 1
            timeout=$((timeout-1))
            if [ "$timeout" -le 0 ]; then
              echo "Timeout when start server."
              exit 1
            fi
          done
          echo "Server is ready."
        env:
          FACEBOOK_VERIFY: ${{ secrets.FACEBOOK_VERIFY }}
          FACEBOOK_SECRET: ${{ secrets.FACEBOOK_SECRET }}
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}