name: Rasa Pro CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  train_and_deploy:
    runs-on: poptech

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Rasa Pro image
        run: |
          sudo docker pull ${{ vars.RASA_IMAGE }}

      - name: Train Rasa model with Rasa Pro
        run: |
          echo ${GITHUB_WORKSPACE} && ls ${GITHUB_WORKSPACE} && sudo docker run --rm -v ${GITHUB_WORKSPACE}:/app \
            -e RASA_PRO_LICENSE=${{ secrets.RASA_PRO_LICENSE }} \
            ${{ vars.RASA_IMAGE }} \
            train -c /app/config.yml --domain /app/domain.yml --endpoints /app/endpoints.yml --data /app/data --out /app/models

      - name: Stop current container
        run: |
          sudo docker container stop github_runner_dgcas2024_rasa

      - name: Run model
        run: |
          sudo docker run --restart unless-stopped -d -v ${GITHUB_WORKSPACE}:/app \
            -e RASA_PRO_LICENSE=${{ secrets.RASA_PRO_LICENSE }} \
            --name github_runner_dgcas2024_rasa
            -p 5005:5005
            ${{ vars.RASA_IMAGE }} \
            run --model /app/models --endpoints /app/endpoints.yml --credentials /app/credentials.yml