name: Rasa Pro CI-CD Pipeline

on:
  push:
    branches:
      - 600x_pop61

jobs:
  train_and_deploy:
    runs-on: poptech

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Rasa Pro image
        run: |
          sudo docker pull ${{ vars.RASA_IMAGE }}

      - name: Train Rasa model with Rasa Pro
        run: |
          echo ${GITHUB_WORKSPACE} && ls ${GITHUB_WORKSPACE} && sudo docker run --rm -v ${GITHUB_WORKSPACE}:/app \
            -e RASA_PRO_LICENSE=${{ secrets.RASA_PRO_LICENSE }} \
            -u $(id -u) \
            ${{ vars.RASA_IMAGE }} \
            train -c /app/config.yml --domain /app/domain.yml --endpoints /app/endpoints.yml --data /app/data --out /app/models

      - name: Stop current container inspect
        run: |
          sudo docker container stop github_runner_dgcas2024_rasa_inspect_6006 && sudo docker container rm github_runner_dgcas2024_rasa_inspect_6006
        continue-on-error: true

      - name: Stop current container action
        run: |
          sudo docker container stop github_runner_dgcas2024_rasa_action_6007 && sudo docker container rm github_runner_dgcas2024_rasa_action_6007
        continue-on-error: true

      - name: Run actions
        run: |
          sudo docker run --restart unless-stopped -d -v ${GITHUB_WORKSPACE}:/app \
            -e RASA_PRO_LICENSE=${{ secrets.RASA_PRO_LICENSE }} \
            -u $(id -u) \
            --name github_runner_dgcas2024_rasa_action_6007 \
            -p 6007:6007 \
            ${{ vars.RASA_IMAGE }} \
            run actions \
            --port 6007
            #--cors "*"

      - name: Run inspect
        run: |
          sudo docker run --restart unless-stopped -d -v ${GITHUB_WORKSPACE}:/app \
            -e RASA_PRO_LICENSE=${{ secrets.RASA_PRO_LICENSE }} \
            -u $(id -u) \
            --name github_runner_dgcas2024_rasa_inspect_6006 \
            -p 6006:6006 \
            ${{ vars.RASA_IMAGE }} \
            inspect --model /app/models --endpoints /app/endpoints.yml \
            --port 6006
            #--cors "*"

      - name: Validate URL
        run: |
          echo "Waiting for actions to be ready..."
          timeout=300
          while ! curl --output /dev/null --silent --fail http://127.0.0.1:6007/health; do
            echo "Waiting for actions to be ready...$timeout"
            sleep 1
            timeout=$((timeout-1))
            if [ "$timeout" -le 0 ]; then
              echo "Timeout when start actions."
              exit 1
            fi
          done
          echo "Actions is ready."

          echo "Waiting for inspect to be ready..."
          timeout=300
          while ! curl --output /dev/null --silent --fail http://127.0.0.1:6006/status; do
            echo "Waiting for inspect to be ready...$timeout"
            sleep 1
            timeout=$((timeout-1))
            if [ "$timeout" -le 0 ]; then
              echo "Timeout when start inspect."
              exit 1
            fi
          done
          echo "Inspect is ready."