name: Rasa Pro CI-CD Pipeline - e2e test 4

on:
  push:
    branches:
      - master
    paths:
      - 'tests/**'
      - '.github/workflows/e2e-test.yml'

jobs:
  run_test_case:
    runs-on: poptech

    steps:
      - name: Backup models directory
        run: |
          mkdir -p /tmp/models_backup
          cp -r models /tmp/models_backup/

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore models directory
        run: |
          cp -r /tmp/models_backup/models models

      - name: Pull Rasa Pro image
        run: |
          sudo docker pull ${{ vars.RASA_IMAGE }}

      - name: Run e2e test
        run: |
          sudo docker run --rm -v ${GITHUB_WORKSPACE}:/app \
            -e RASA_PRO_LICENSE=${{ secrets.RASA_PRO_LICENSE }} \
            -e RASA_PRO_BETA_E2E_ASSERTIONS=true \
            -e RASA_PRO_BETA_E2E_CONVERSION=true \
            -u $(id -u) \
            ${{ vars.RASA_IMAGE }} \
            test e2e --model /app/models --endpoints /app/endpoints.yml /app/tests/e2e_test_cases.yml